name: 'JavaScript Action'
description: 'Adds PR changes as comments'
author: 'Nik'

# Define your inputs here.
inputs:
  owner:
    description: 'Owner of the repository'
    required: true
  repo:
    description: 'Repository name'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  token:
    description: 'GitHub token'
    required: true

runs:
  using: node20
  main: dist/index.js
